version: 2.1

jobs:
  build:
    working_directory: ~/intertwine

    docker:
    - image: collegevine/rails-build

    parallelism: 1

    steps:
    - checkout: { path: "~/intertwine" }

    - restore_cache:
        keys:
          - intertwine-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "bower.json" }}
          - intertwine-v2-{{ .Branch }}-

    - run: npm install && sysconfcpus -n 2 npm run build && sysconfcpus -n 2 npm run test

    - save_cache:
        key: intertwine-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "bower.json" }}
        paths:
          - bower_components
          - node_modules
          - output
          - ~/.cache
